### ISSUE TITLE
Hidden window when second screen disconnected

### ISSUE THREAD

**Issue by educarvalhu** [pure-data/pure-data#1619]
If a patch is created with some window (parent or child/subpatch) and is saved on a second screen, after reopening the patch on a single screen, the PD tries to run the windows on the second screen even though it does not exist, so it is not possible preview the patch.

My operating system: Windows 11 Pro N 21H2 (64bit);
Two screen: LG ultrwide desktop with Blitzwolf pcm8 or LenovoThinkPad T480s Notebook with Blitzwolf pcm8 (as in the video);
Pd version 0.52.2;

**Comment by umlaeute** [comment]
which Pd version? which OS (obviously some 64bit Windows, but which one?)? which screen layout?
do you have an example patch?

iirc, there's actually some code in place that should wrap the window position to the available screen size. so i wonder why it doesn't kick in.
(i haven't checked the code right now, but probably this only works if the coordinates are positive, allowing you to *hide* patches off-screen with negative coordinates (which would make it a "feature", that could get triggered inadvertadly by some whacky screen layout)

**Comment by Lucarda** [comment]
@educarvalhu  i can confirm this behavior on Windows11 (and IIRC I'd seen it on win10 and earlier).

@umlaeute  #1627 works Ok for me.

**Comment by umlaeute** [comment]
i'm still not entirely sure whether there is some merit in allowing intentionally off-screen canvases (probably there is none)

**Comment by educarvalhu** [comment]
Hi guys, sorry for the delay, I wanted to take the time to record a video exemplifying the case.

My operating system: Windows 11 Pro N 21H2;

Two screen: LG ultrwide desktop with Blitzwolf pcm8 or LenovoThinkPad T480s Notebook with Blitzwolf pcm8 (as in the video);

Pd version 0.52.2;

It happens with any patch. In the video I created a totally new patch to exemplify.

Example video hosted on Google Drive: https://drive.google.com/file/d/15LILZtMnUDZcBP1oaV-rv8YDrbuBHNeb/view?preview

**Comment by Lucarda** [comment]
If you need a "now" solution (you can't wait until the above mentioned PR gets merged) you can edit "tcl/pdtk_canvas.tcl".

1. close Pd

2. backup `pdtk_canvas.tcl` in a safe place in case something goes wrong.

3. Open `pdtk_canvas.tcl` on a plain text editor (recommended https://notepad-plus-plus.org/)

4. change line 42 from:

````
if {$::tcl_version < 8.5 || \
````
  
to 

````
if {[tk windowingsystem] eq "win32" || \
    $::tcl_version < 8.5 || \
````

so you end up having:

````
if {[tk windowingsystem] eq "win32" || \
    $::tcl_version < 8.5 || \
        ($::tcl_version == 8.5 && \
             [tk windowingsystem] eq "aqua" && \
             [lindex [split [info patchlevel] "."] 2] < 13) } {
			 
			 ...
			 
``````````

5. save `pdtk_canvas.tcl`.

6. start Pd (voilà). 

Note: i'm not sure if there's a way to support hot-swapping. I didn't test that, may be it also work. if not just restart Pd when you change monitor setups.

**Comment by umlaeute** [comment]
fixed in 10191a67f6d7bd77d82ee08838f92b299c45fa8a (which has been merged into `master` by means of #1633 )

**Comment by edsonedge** [comment]
This is still an issue with PD vanilla version 0.53.2 on my Windows 11 Home 22H2

**Comment by ElwinBran** [comment]
Solution may sometimes be to play around with the window settings (win + arrow key is the shortcut)
