### ISSUE TITLE
multiple NULL-pointer dereferences of gl->gl_editor when using donecanvasdialog in a GOP

### ISSUE THREAD

**Issue by umlaeute** [pure-data/pure-data#2653]
somewhat related to https://github.com/pure-data/pure-data/issues/2636 (but apparently not fixed by #2641 resp #2634 )

I have an abstraction that "plots" matrices (in iemmatrix) with data structures.

it uses `donecanvasdialog` to set the size of the window and whatnot.

afaik, there are *multiple* NULL-pointer dereferences of `gl->gl_editor`.

current `develop` 8bade9a0c9c5927c1fe115e9cdd53476653bf039 crashes when opening either the object itself (as a top-level patch) or as a GOP-abstraction. afaict, these crashes are not exactly the same.

the code is probably not the cleanest (and uses `donecanvasdialog`, which is actually a private, see #627), and it throws an error with Pd-0.55 when opened as a standalone patch (that is: not as an abstraction within the patch).

it shouldn't crash though.

attached is a stripped down version of the patch.
`mtx_plot-help.pd` is just to call the object (`[mtx_plot]`) as an abstraction
[mtx_plot.zip](https://github.com/user-attachments/files/21037854/mtx_plot.zip)

(the abstractions should be self-contained; all references to external libraries like iemmatrix have been removed)

**Comment by millerpuckette** [comment]
OK, so I can work around this by simply checking if the window is visible and refusing donedialog() if it isn't... but would it be important to you to be able to send "dialog" messages to not-yet-visible patches?

**Comment by umlaeute** [comment]
what would be important for me, is actually only to be able to set the GOP rectangle programmatically (#627).

I want to be able to do this at loadbang time (without caring, whether the patch is already visible or not)

**Comment by Spacechild1** [comment]
When I open `mtx_plot-help.pd` on latest master (17ab82272cd93c99e6807e69d240194ad7de30dd) I actually seem to get an infinite loop: Pd doesn't respond and `pd.com` runs at 100% CPU load. The patch works just fine on Pd 0.55.2.

I think we have to do something about it. The "goprect" method has been only introduced now, so patch authors didn't have a chance to move away from (ab)using "donecanvasdialog". I guess we still have to support it until Pd 0.57 or 0.58...

**Comment by ben-wes** [comment]
i'm surprised you seem to get an infinite loop. for me, it also crashes immediately here on macos.

bisect result: 1a4cf8e3be9691ca13fcf5333b35c321b4efefa6 is the first bad commit

<details>
<summary>LLDB output</summary>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xfd8fc1a26178)
    frame #0: 0x000000010006c77c pd`outlet_anything(x=<unavailable>, s=0x000060000226ece0, argc=14, argv=0x000000016fdfc180) at m_obj.c:641:27 [opt]
   638          outlet_stackerror(x);
   639      else
   640          for (oc = x->o_connections; oc; oc = oc->oc_next)
-> 641              typedmess(oc->oc_to, s, argc, argv);
   642      stackcount_release();
   643  }
```

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xfd8fc1a26178)
  * frame #0: 0x000000010006c77c pd`outlet_anything(x=<unavailable>, s=0x000060000226ece0, argc=14, argv=0x000000016fdfc180) at m_obj.c:641:27 [opt]
    frame #1: 0x0000000100066040 pd`binbuf_eval(x=<unavailable>, target=0x000060000016a290, argc=0, argv=0x0000000000000000) at m_binbuf.c:764:17 [opt]
    frame #2: 0x000000010006c434 pd`outlet_bang(x=<unavailable>) at m_obj.c:582:13 [opt]
    frame #3: 0x0000000100081c20 pd`trigger_list(x=0x000060000374d180, s=0x0000000100114fe8, argc=0, argv=0x0000000000000000) at x_connective.c:1048:13 [opt]
    frame #4: 0x000000010006c434 pd`outlet_bang(x=<unavailable>) at m_obj.c:582:13 [opt]
    frame #5: 0x0000000100066040 pd`binbuf_eval(x=<unavailable>, target=0x000060000016a2e0, argc=0, argv=0x0000000000000000) at m_binbuf.c:764:17 [opt]
    frame #6: 0x000000010006c434 pd`outlet_bang(x=<unavailable>) at m_obj.c:582:13 [opt]
    frame #7: 0x000000010006a798 pd`pd_typedmess(x=<unavailable>, s=0x000060000226e780, argc=<unavailable>, argv=<unavailable>) at m_class.c:1155:9 [opt]
    frame #8: 0x000000010006acf0 pd`pd_vmess(x=0x0000600002c4f1e0, sel=0x000060000226e780, fmt=<unavailable>) at m_class.c:1196:5 [opt]
    frame #9: 0x00000001000287c4 pd`canvas_loadbangsubpatches(x=0x0000600001e6ec00) at g_canvas.c:1150:13 [opt]
    frame #10: 0x00000001000288b0 pd`canvas_loadbangabstractions [inlined] canvas_loadbang(x=0x0000600001e6ec00) at g_canvas.c:1157:5 [opt]
    frame #11: 0x00000001000288a8 pd`canvas_loadbangabstractions(x=<unavailable>) at g_canvas.c:1124:17 [opt]
    frame #12: 0x00000001000287f0 pd`canvas_loadbang(x=0x0000600001e6eb00) at g_canvas.c:1156:5 [opt]
    frame #13: 0x000000010006a798 pd`pd_typedmess(x=<unavailable>, s=0x000060000226e780, argc=<unavailable>, argv=<unavailable>) at m_class.c:1155:9 [opt]
    frame #14: 0x000000010006acf0 pd`pd_vmess(x=0x0000600001e6eb00, sel=0x000060000226e780, fmt=<unavailable>) at m_class.c:1196:5 [opt]
    frame #15: 0x000000010006e248 pd`pd_doloadbang at m_pd.c:313:9 [opt]
    frame #16: 0x000000010002acf0 pd`glob_evalfile(ignore=<unavailable>, name=<unavailable>, dir=<unavailable>) at g_canvas.c:2266:9 [opt]
    frame #17: 0x000000010002ad48 pd`glob_open(ignore=<unavailable>, name=<unavailable>, dir=<unavailable>, f=<unavailable>) at g_canvas.c:2287:10 [opt]
    frame #18: 0x000000010006a798 pd`pd_typedmess(x=<unavailable>, s=<unavailable>, argc=<unavailable>, argv=<unavailable>) at m_class.c:1155:9 [opt]
    frame #19: 0x0000000100066040 pd`binbuf_eval(x=<unavailable>, target=0x00000001001150a8, argc=0, argv=0x0000000000000000) at m_binbuf.c:764:17 [opt]
    frame #20: 0x0000000100071b04 pd`socketreceiver_read(x=0x0000600003760b00, fd=8) at s_inter.c:714:26 [opt]
    frame #21: 0x000000010007117c pd`sys_domicrosleep(microsec=0) at s_inter.c:254:13 [opt]
    frame #22: 0x000000010007227c pd`sys_pollgui at s_inter.c:1088:24 [opt]
    frame #23: 0x000000010006eff4 pd`m_mainloop [inlined] m_pollingscheduler at m_sched.c:490:9 [opt]
    frame #24: 0x000000010006ef90 pd`m_mainloop at m_sched.c:643:13 [opt]
    frame #25: 0x0000000100075ea4 pd`sys_main(argc=<unavailable>, argv=<unavailable>) at s_main.c:460:15 [opt]
    frame #26: 0x00000001834a6b98 dyld`start + 6076
```
</details>

**Comment by millerpuckette** [comment]
should be fixed in commit 3a01cb051bd5340c871511b3982de953b7eb0004

**Comment by ben-wes** [comment]
i can load @umlaeute's test patch above with this fix. but if i try to create the `mtx_plot` object (or duplicate it), this still crashes for me:

<details>
<summary>more LLDB output (but this looks pretty similar as above)</summary>

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3cadb9219238)
    frame #0: 0x000000010006c784 pd`outlet_anything(x=<unavailable>, s=0x000060000279c480, argc=14, argv=0x000000016fdfc270) at m_obj.c:641:27 [opt]
   638          outlet_stackerror(x);
   639      else
   640          for (oc = x->o_connections; oc; oc = oc->oc_next)
-> 641              typedmess(oc->oc_to, s, argc, argv);
   642      stackcount_release();
   643  }
   644
```

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3cadb9219238)
  * frame #0: 0x000000010006c784 pd`outlet_anything(x=<unavailable>, s=0x000060000279c480, argc=14, argv=0x000000016fdfc270) at m_obj.c:641:27 [opt]
    frame #1: 0x0000000100066048 pd`binbuf_eval(x=<unavailable>, target=0x0000600000484670, argc=0, argv=0x0000000000000000) at m_binbuf.c:764:17 [opt]
    frame #2: 0x000000010006c43c pd`outlet_bang(x=<unavailable>) at m_obj.c:582:13 [opt]
    frame #3: 0x0000000100081c28 pd`trigger_list(x=0x000060000328cc40, s=0x0000000100114fe8, argc=0, argv=0x0000000000000000) at x_connective.c:1048:13 [opt]
    frame #4: 0x000000010006c43c pd`outlet_bang(x=<unavailable>) at m_obj.c:582:13 [opt]
    frame #5: 0x0000000100066048 pd`binbuf_eval(x=<unavailable>, target=0x00006000004846c0, argc=0, argv=0x0000000000000000) at m_binbuf.c:764:17 [opt]
    frame #6: 0x000000010006c43c pd`outlet_bang(x=<unavailable>) at m_obj.c:582:13 [opt]
    frame #7: 0x000000010006a7a0 pd`pd_typedmess(x=<unavailable>, s=0x0000600002797f20, argc=<unavailable>, argv=<unavailable>) at m_class.c:1155:9 [opt]
    frame #8: 0x000000010006acf8 pd`pd_vmess(x=0x000060000298d3b0, sel=0x0000600002797f20, fmt=<unavailable>) at m_class.c:1196:5 [opt]
    frame #9: 0x00000001000287c4 pd`canvas_loadbangsubpatches(x=<unavailable>) at g_canvas.c:1150:13 [opt]
    frame #10: 0x00000001000287fc pd`canvas_loadbang(x=<unavailable>) at g_canvas.c:1157:5 [opt] [artificial]
    frame #11: 0x000000010002f71c pd`canvas_dopaste [inlined] glist_donewloadbangs(x=<unavailable>) at g_editor.c:3997:17 [opt]
    frame #12: 0x000000010002f6e8 pd`canvas_dopaste(x=0x0000600001b92600, b=<unavailable>) at g_editor.c:4130:9 [opt]
    frame #13: 0x0000000100036de8 pd`canvas_duplicate(x=0x0000600001b92600) at g_editor.c:4357:9 [opt]
    frame #14: 0x000000010006a7a0 pd`pd_typedmess(x=<unavailable>, s=<unavailable>, argc=<unavailable>, argv=<unavailable>) at m_class.c:1155:9 [opt]
    frame #15: 0x0000000100066048 pd`binbuf_eval(x=<unavailable>, target=0x0000600000492120, argc=0, argv=0x0000000000000000) at m_binbuf.c:764:17 [opt]
    frame #16: 0x0000000100071b0c pd`socketreceiver_read(x=0x0000600003296100, fd=8) at s_inter.c:714:26 [opt]
    frame #17: 0x0000000100071184 pd`sys_domicrosleep(microsec=0) at s_inter.c:254:13 [opt]
    frame #18: 0x0000000100072284 pd`sys_pollgui at s_inter.c:1088:24 [opt]
    frame #19: 0x000000010006effc pd`m_mainloop [inlined] m_pollingscheduler at m_sched.c:490:9 [opt]
    frame #20: 0x000000010006ef98 pd`m_mainloop at m_sched.c:643:13 [opt]
    frame #21: 0x0000000100075eac pd`sys_main(argc=<unavailable>, argv=<unavailable>) at s_main.c:460:15 [opt]
    frame #22: 0x00000001834a6b98 dyld`start + 6076
```
</details>

**Comment by millerpuckette** [comment]
Hmm... mtx is sending 14 arguments to the (12-arg) message, so the extra "1 1" is interpreted as new text to recreate the object (thereby committing suicide).  Not good.  Anyway I've put in another workaround (sigh...)
Should be fixed now.

**Comment by ben-wes** [comment]
confirming happy bandits.

**Comment by umlaeute** [comment]
seems to work for me as well.

thanks
(and even more thanks for the new `goprect` message)
