### ISSUE TITLE
path problem using "clone" when editing the abstraction

### ISSUE THREAD

**Issue by ch-nry** [pure-data/pure-data#410]
Here is a patch to replicate the problem:

[test_clone_and_path.zip](https://github.com/pure-data/pure-data/files/2273799/test_clone_and_path.zip)

This problem happens only if abstractions are used thanks to a "declare -path" in the parent patch.
In this situation, when editing a clonned abstraction, other declared abstraction can not be found.
They are found only when clone is created or reload (thanks to saving it's abstraction).

**Comment by danomatika** [comment]
@Spacechild1 maybe you can look at this?

**Comment by Spacechild1** [comment]
unfortunately I'm running out of time... what I noticed: [declare] outside [clone] also didn't work in Pd 0.48. the reason is basically that cloned abstractions are created as root abstractions, so they don't inherit the search paths of the environment where the [clone] object lives. this could be changed.

what's new in Pd 0.49 is that when you save the cloned parent and other instances are remade, the child abstractions inside *not cloned* instances haven't been loaded. now this is weird! I guess this is something for @millerpuckette 

I think getting [declare] to work inside clone could be postponed to 0.49.1 since it's not a new issue but the regression introduce with 0.49 should be fixed.

**Comment by danomatika** [comment]
Is this fixed in 0.50? If not, let's move it to the 0.51 milestone.

**Comment by ch-nry** [comment]
I am not able to replicate the problem using 0.50, so I think it is fixed.

**Comment by umlaeute** [comment]
i don't think it's fixed.
at least here (Pd-0.50.0-1 as packaged in Debian) the problem persists.
